FROM drupal:7-apache

ENV CIVICRM_VERSION 5.13.5
ENV DRUSH_VERSION 8.2.3

# Other envars
# ENV MYSQL_DATABASE
# ENV MYSQL_USER
# ENV MYSQL_PASSWORD
# ENV MYSQL_HOST
# ENV MYSQL_PORT
# ENV DRUPAL_HASH_SALT

COPY Makefile Makefile
COPY docker/civicrm-drupal /

RUN make
