version: "3"

services:
  civicrm-drupal:
    build: .
    ports:
      - "8080:80"
      - "4433:443"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: civicrm-drupal
      MYSQL_USER: civicrm-drupal
      MYSQL_PASSWORD: notsecure
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DRUPAL_HASH_SALT: salt
      BASEURL: localhost:4433

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notsecure
      MYSQL_DATABASE: civicrm-drupal
      MYSQL_USER: civicrm-drupal
      MYSQL_PASSWORD: notsecure
