# CodePipeline

data "aws_iam_policy_document" "codepipeline-assume-role-policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["codepipeline.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "codepipeline" {
  name               = "role-codepipeline-${var.project_name}"
  path               = "/${var.project_name}/"
  assume_role_policy = "${data.aws_iam_policy_document.codepipeline-assume-role-policy.json}"
}

# TODO make this more specific. This is a pruned version from the
# autogenerated policy, but it's still quite permissive.

data "aws_iam_policy_document" "codepipeline_policy" {
  statement {
    actions = [
      "iam:PassRole"
    ],
    resources = [
      "*"
    ],
    condition {
      test = "StringEqualsIfExists"
      variable = "iam:PassedToService"
      values = [
	"cloudformation.amazonaws.com",
	"elasticbeanstalk.amazonaws.com",
	"ec2.amazonaws.com",
	"ecs-tasks.amazonaws.com"
      ]
    }
  }

  statement {
    actions = [
      "codedeploy:CreateDeployment",
      "codedeploy:GetApplication",
      "codedeploy:GetApplicationRevision",
      "codedeploy:GetDeployment",
      "codedeploy:GetDeploymentConfig",
      "codedeploy:RegisterApplicationRevision"
    ],
    resources = [
      "*"
    ],
  }

  statement {
    actions = [
      "elasticbeanstalk:*",
      "ec2:*",
      "elasticloadbalancing:*",
      "autoscaling:*",
      "cloudwatch:*",
      "s3:*",
      "sns:*",
      "cloudformation:*",
      "rds:*",
      "sqs:*",
      "ecs:*"
    ],
    resources = [
      "*"
    ],
  }

  statement {
    actions = [
      "codebuild:BatchGetBuilds",
      "codebuild:StartBuild"
    ],
    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "ecr:DescribeImages"
    ],
    resources = [
      "*"
    ]
  }

}

resource "aws_iam_role_policy" "codepipeline" {
  name = "policy-codepipeline-${var.project_name}"
  role = "${aws_iam_role.codepipeline.id}"
  policy = "${data.aws_iam_policy_document.codepipeline_policy.json}"
}

# CodeBuild

data "aws_iam_policy_document" "codebuild-assume-role-policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["codebuild.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "codebuild" {
  name               = "role-codebuild-${var.project_name}"
  path               = "/${var.project_name}/"
  assume_role_policy = "${data.aws_iam_policy_document.codebuild-assume-role-policy.json}"
}

data "aws_iam_policy_document" "codebuild_policy" {
  statement {
    sid = 1
    actions = [
	"s3:PutObject",
	"s3:GetBucketAcl",
	"s3:GetBucketLocation",
	"s3:GetObject",
	"s3:GetObjectVersion"
      ]
    resources = [
	"*"
    ]
  }

  statement {
    sid = 2
    actions = [
	"ecr:BatchCheckLayerAvailability",
	"ecr:CompleteLayerUpload",
	"ecr:GetAuthorizationToken",
	"ecr:InitiateLayerUpload",
	"ecr:PutImage",
	"ecr:UploadLayerPart"
    ]
    resources = [
      "*"
    ]
  }

  statement {
    sid = 3
    actions = [
	"logs:CreateLogGroup",
	"logs:CreateLogStream",
	"logs:PutLogEvents"
    ]
    resources = [
      "*"
    ]
  }
}

resource "aws_iam_role_policy" "codebuild" {
  name = "policy-codebuild-${var.project_name}"
  role = "${aws_iam_role.codebuild.id}"
  policy = "${data.aws_iam_policy_document.codebuild_policy.json}"
}

# ECS

data "aws_iam_policy_document" "ecs-assume-role-policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ecs.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ecs" {
  name               = "role-ecs-${var.project_name}"
  path               = "/${var.project_name}/"
  assume_role_policy = "${data.aws_iam_policy_document.codepipeline-assume-role-policy.json}"
}

data "aws_iam_policy_document" "ecs_policy" {
  statement {
    actions = [
      "*"
    ],
    resources = [
      "*"
    ]
  }
}

resource "aws_iam_role_policy" "ecs" {
  name = "policy-ecs-${var.project_name}"
  role = "${aws_iam_role.ecs.id}"
  policy = "${data.aws_iam_policy_document.ecs_policy.json}"
}

# EC2

data "aws_iam_policy_document" "ec2-assume-role-policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ec2" {
  name               = "role-ec2-${var.project_name}"
  path               = "/${var.project_name}/"
  assume_role_policy = "${data.aws_iam_policy_document.ec2-assume-role-policy.json}"
}

resource "aws_iam_role_policy_attachment" "ecs-ec2" {
  role       = "${aws_iam_role.ec2.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
}

resource "aws_iam_instance_profile" "ec2" {
  name = "instance-profile-${var.project_name}"
  role = "${aws_iam_role.ec2.id}"
}
